name: test
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "^1.22.5"
          check-latest: true

      - name: Check out code
        uses: actions/checkout@v3

      - name: Mod tidy
        run: go mod tidy

      - name: Test
        run: make test
